List<String> images = [
  'img0.svg',
  'img1.svg',
  'img2.svg',
  'img3.svg',
  'img4.svg',
  'img5.svg'
];
List<String> titles = [
  'Happiness',
  'Exercise',
  'No Junk Food',
  'Study',
  'Sleep',
  'Positive Mindset'
];
Map<String, List<String>> habitMap = {
  'Happiness': [
    'Clean the bed sheets and \ntidy a room in your home',
    'Listen to music that you \nused to listen in your\n childhood',
    'Meditate for 10 minutes',
    'Treat yourself some \nflowers or a walk \nin the garden or\n somewhere new',
    'Compliment someone today,\nincluding yourself',
    'Dance your heart out \ntoday to some of \nyour loved pop songs!',
    'Take yourself our\n for a lunch or \ncook from scratch!',
    'Do something creative',
    'Take a nice relaxing \nhot bath or shower,\n and watch the sunrise or sunset',
    'Create a board \non any website for \nthing that you love',
    'Bake a cake!',
    'Go out for a \nnice walk and \nlisten to birds',
    'Call a distant or \nolder friend of yours, \nor have a nice talk \nwith your family',
    'Read a book!',
    'Learn something new today!',
    'Indulge yourself in \ntrying that new thing!',
    'Help someone',
    'Do yoga or exercise \nfor 20 minutes',
    'Upgrade your level up \nin anything',
    'Celebrate every win today!',
    'Start a journal. \nEat healthy.'
  ],
  'Exercise': [
    '(take break of 30 seconds after each exercise)\n20 jumping jacks,\n10 alternating lunges,\n15 crunches,\n5 push-ups(if possible),\n20-second plank',
    '(take break of 30 seconds after each exercise)\n10 burpees,\n10 sit-ups,\n15 tricep dips,\n20 butt kicks,\n20 toe touch crunches',
    '(take break of 30 seconds after each exercise)\n20 mountain climbers,\n5 push-ups(if possible),2\n5 crunches,\n20 walking lunges,\n20-second wall sit',
    '(take break of 30 seconds after each exercise)\n15 butt kicks,\n15 tricep dips,\n10 burpees,\n12 squats,\n20 toe touch crunches',
    '(take break of 30 seconds after each exercise)\n25 jumping jacks,\n15 step-ups,\n10 sit-ups,\n20 ab bikes,\n20 alternating lunges',
    'Rest day!!!',
    '(take break of 30 seconds after each exercise)\n30 mountain climbers,\n20 squats,\n8 push-ups(if possible),\n20 butt kicks,\n25 toe touch crunches',
    '(take break of 30 seconds after each exercise)\n35 jumping jacks, \n30 alternative lunges, \n30 crunches, \n8 push-ups(if possible), \n25-second plank',
    '(take break of 30 seconds after each exercise)\n12 burpees, \n10 sit-ups, \n15 tricep dips,\n 25 butt kicks, \n25 toe touch crunches',
    '(take break of 30 seconds after each exercise)\n30 mountain climbers, \n8 push-ups(if possible), \n30 crunches, \n20 walking lunges, \n30-second wall sit',
    '(take break of 30 seconds after each exercise)\n25 butt kicks, \n15 tricep dips, \n12 burpees, \n20 squats, \n30 toe touch crunches',
    '(take break of 30 seconds after each exercise)\n30 jumping jacks, \n20 step-ups, \n15 sit-ups, \n20 ab bikes, \n25 alternating lunges',
    'Rest day!!!',
    '(take break of 30 seconds after each exercise)\n40 mountain climbers, \n20 squats, \n10 push-ups(if possible), \n30 butt kicks, \n25 toe touch crunches',
    '(take break of 30 seconds after each exercise)\n40 jumping jacks, \n30 alternative lunges, \n30 crunches, \n8 push-ups(if possible), \n25-second plank',
    '(take break of 30 seconds after each exercise)\n12 burpees, \n10 sit-ups, \n15 tricep dips, \n25 butt kicks, \n25 toe touch crunches',
    '(take break of 30 seconds after each exercise)\n30 mountain climbers,\n8 push-ups(if possible), \n30 crunches, \n20 walking lunges, \n30-second wall sit',
    '(take break of 30 seconds after each exercise)\n25 butt kicks, \n15 tricep dips, \n12 burpees, \n20 squats, \n30 toe touch crunches',
    '(take break of 30 seconds after each exercise)\n30 jumping jacks, \n20 step-ups, \n15 sit-ups, \n20 ab bikes, \n25 alternating lunges',
    'Rest day!!!',
    '(take break of 30 seconds after each exercise)\n40 mountain climbers, \n20 squats, \n10 push-ups(if possible), \n30 butt kicks, \n25 toe touch crunches'
  ],
  'No Junk Food': [
    'Add 3 vegetables \nin your meals',
    'Have almonds,cashews\n or other nuts \ninstead of candy bars',
    'Replace white bread \nin your diet with \nRoti/Chapati or whole grain bread',
    'Eat a fruit bowl\n(freshly cut fruit)',
    'No wheat flour in meals today',
    'Take water instead\n of other drinks',
    'No packed munchies,\neat apple or any\n other fruit',
    'No fuzzy drinks. \nTake water or fruit juice instead.',
    'No outside and/or fast food.\n Eat homemade healthy \nalternatives of fast food.',
    'Try vegetarian or\n vegan food',
    'Try new vegan dishes',
    'Eat dates/jaggery instead\n of sugary bars\n(its time to finally replace sugar!)',
    'Replace potato with\n sweet potato and \nmake a new dish out of it!',
    'Drink atleast 1.5 litres\n of water today',
    'No refined sugar today,\n replace it with dates/jaggery \nfor your sugar cravings',
    'No dairy product \nconsumption today',
    'Eat sweet fruits for\n satisfying your sugar cravings',
    'Include more greens \nin your diet',
    'Have an oatmeal for\n breakfast today!',
    'No meat for today!\n Time to try vegetarian again!',
    'Since you have come\n this far, celebrate it \nand honor yourself! \nTreat yourself with \npiece of dark chocolate!'
  ],

  'Study': [
    'Study continuously with \nfocus for 20 minutes',
    'Study continuously with \nfocus for 20 minutes',
    'Study continuously with \nfocus for 20 minutes',
    'Study continuously with \nfocus for 30 minutes',
    'Break!',
    'Study continuously with \nfocus for 20 minutes',
    'Study continuously with \nfocus for 30 minutes',
    'Study continuously with \nfocus for 30 minutes',
    'Study continuously with \nfocus for 40 minutes',
    'Break!',
    'Study continuously with \nfocus for 20 minutes',
    'Study continuously with \nfocus for 30 minutes',
    'Study continuously with \nfocus for 40 minutes',
    'Study continuously with \nfocus for 40 minutes',
    'Break!',
    'Study continuously with \nfocus for 20 minutes',
    'Study continuously with \nfocus for 30 minutes',
    'Study continuously with \nfocus for 40 minutes',
    'Study continuously with \nfocus for 40 minutes',
    'Break!',
    'Tap on your back for \nhabit completion and celebrate!'
  ],
  'Sleep': [
    'Fix your lights out time \nand sleep time. Paste the note \non your vision board today',
    'Try not to reset/stretch \nthat schedule more than \n2 hours on weekends,especially',
    'Stop consuming caffeine\n 6 hours before your \nlights out time',
    'Stop drinking alcohol \nminimum of 2 hours \nbefore lights out',
    'Begin your sleep preparation\n approximately 1 hour\n before lights out',
    'Its best to turn off\n all your electronic devices \n2-3 hours before lights out time.\n Atleast an hour, realistically.',
    'Read book in your no-screen \ntime before sleep',
    'Dim your home lighting \nto decrease blue-light exposure. \nKeep only study lights on \nfor reading books, \nif you want to.',
    'Note down all the tasks \nthat are important and you \nexpect to complete them \ntomorrow as soon as possible.',
    'Complete any tasks that \nwill help you quickly jump \nstart your morning the next day,\n like packing lunch,\npreparing coffee maker,etc.',
    'Complete your bathroom \nself-care or night-care routine \nquickly and efficiently.',
    'Enjoy your relax time \nby doing some basic \nnight stretches',
    'Make all adjustments \nfor your sleep',
    'Go for a brisk walk',
    'Take a hot bath or \nshower to relax yourself',
    'Reserve bed for sleep only.\n Not for other daily rituals or tasks.',
    'Start a night ritual; \nlike listening to soothing music,\ntaking a warm glass of milk or\n taking a hot bath/shower',
    'Eat, but in a limited quantity.',
    'Choose one space tonight\n in you home to de-clutter\n your mind',
    'Go to your de-clutter space\n and calm down',
    'Turn off the lights at\n assigned lights-out time \nand go to your cozy bed \nfor a blissful sleep!'
  ],
  'Positive Mindset': [
    'Pretend that every person\n you see is a long, lost friend\n and you love them as \nthey are to pieces!',
    'Pick your favourite \ninspiring quote and post \nit in a prominent place \nat you home!',
    'Pay attention to what \nenergises you rather \nthan what drains you',
    'Do less of what drains \nyou and more of what \nenergises you today',
    'Throw your to-do list\n and decide your personality traits\n that you want. Start now and \nwork for it everyday.',
    'Exercise for atleast \n5 minutes today',
    'Listen to a song that \nmakes you feel happy!',
    'Make eye contact and \nsmile to everyone you see!',
    'Choose only one thing of your \nto-do list to accomplish today',
    'Treat someone you love\n(be it friends,family, \npartner or yourself) \nto something amazing today!',
    'Write down thing that \nmake you happy and keep \nit in your bag to look\n at when you feel down',
    'Choose one space in you\n home to de-clutter your\n mind! Block out 20 minutes\n each day and you are\n good to go!',
    'Meditate and think \nof your mind as a snow ball,\n it needs to be still\n to stay clear and focused',
    'Take some time to reflect\n upon the question that \nwhat all can you control \nand what can you surrender\n to a higher power, or simply, \nthe universe.',
    'Start a Vision Board. \nWhen you see it, \nyou will create it.',
    'Take a step out of your\n comfort zone and get \none step closer to your goal.\n Do this everyday!',
    'Turn all your negative\n thoughts and mend them \nto positive ones,finally, today. \nDo this everytime you \nfind a negative thought!',
    'Fake it till you make it.\n Fake the ting that you want \nin yourself. You will \ngradually get it.',
    'Write a letter to future \nyou and pop it on your \nvision board. Check it \nevery month atleast.',
    'Start a mood journal\n and record your daily moods \nand reactions everyday. \nYou will observe some pattern.',
    'Since you have come this far, \ncelebrate it and honor yourself!'
  ],
};
